import qrcode
import random
import string
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Concatenate, Conv2D, UpSampling2D, Reshape
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.applications import VGG16

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

import cv2
import os
from PIL import Image


import tensorflow_datasets as tfds
from keras.layers import Dense, LeakyReLU
from matplotlib import pyplot

from ray.tune.schedulers import ASHAScheduler
from ray.air.config import RunConfig

import json
import ray
from ray import tune
from ray.air import session


ray.init(dashboard_port=8265)
"""# Global Speicfications"""

image_width = 256
image_height = 256
channels = 3

"""# Functions

## Load Real Samples
"""

def load_real_samples(target_shape, num_samples_to_take = 500):
    constant_label = 1
    caltech_builder = tfds.builder('mnist')
    caltech_builder.download_and_prepare()
    dataset = caltech_builder.as_dataset(split='train')

    shuffled_dataset = dataset.shuffle(buffer_size=num_samples_to_take)
    subset_dataset = shuffled_dataset.take(num_samples_to_take)

    num_images_in_subset = tf.data.experimental.cardinality(subset_dataset).numpy()
    
    images, labels = [], []
    for example in subset_dataset:
        example['image'] = tf.image.resize(example['image'], target_shape)
        images.append(example['image'].numpy())
        labels.append(constant_label)

    images_array = np.array(images)
    labels_array = np.array(labels, dtype=np.int64)

    num_images_in_subset = len(images_array)
    print(f"Number of images in subset_dataset_with_labels: {num_images_in_subset}")

    return images_array, labels_array

"""## Generate QR Codes"""

LETTERS = string.ascii_lowercase + ' ' # letters and space
EOI = '#' # end of input
MAX_SIZE = 11 # max input/output size
ALL_CHAR_CLASSES = LETTERS + EOI # all available classes

# define a function for a QR code generation
# box_size is an option to manage size of an output image
def make_qr(text, box_size=12, target_size=(256, 256)):
    qr = qrcode.QRCode(
        version=1,
        box_size=box_size,
        border=0
    )
    qr.add_data(text)
    qr.make(fit=True)
    qr_image = qr.make_image(fill_color="black", back_color="white")

    # Resize the QR code image to the target size
    resized_image = qr_image.resize(target_size)

    return np.asarray(resized_image, dtype='float')

# a function to generate a train data set
# output: (numpy array of images, list of corresponding texts)
def generate_dataset(n_of_samples, min_size = 1, max_size = 11):
    data = []
    labels = []
    report_step = int(n_of_samples * .1)
    report = report_step
    print("Generating")
    for i in range(n_of_samples):
        if i == report:
            
            report = report + report_step
        #select size of the string to be embedded in a QR Code randonly between 1 and 11
        size = random.randint(min_size, max_size)
        #generate the string using random letters and space
        s = ''.join(random.choice(LETTERS) for i in range(size))
        #make the QR Code
        img = make_qr(s)
        #ensure the size is 256 x 256 pixels
        #assert img.size == (256,256)
        qr = np.asarray(img, dtype='float')
        #resize QR to match the host image

        #Append the QR code to the data list
        data.append(qr)
        #Append the String of random size generated using random letters to the label list
        labels.append(s)
    print("Done:", "100", "%")
    return (np.asarray(data), labels)

"""## Create Dataset for Discriminator 1

For Discriminator 1, that is supposed to ensure that the image generated by the generator is similar to the host image, we need the following dataset:

consider the data_size i.e., the number of data samples in a batch is n, then dataset should contain n/2 real images and n/2 fake images.
"""

def create_dataset_d1(real_samples, real_labels, fake_samples, fake_labels, data_size):
  data_batch = []
  labels_batch = []
  
  for i in range (int(data_size/2)):
    random_number = random.randint(0, int(data_size/2))
    data_batch.append(real_samples[random_number])
    labels_batch.append(real_labels[random_number])

  for i in range (int(data_size/2)):
    random_number = random.randint(0, int(data_size/2))
    data_batch.append(fake_samples[random_number])
    labels_batch.append(fake_labels[random_number])

  data_batch = np.asarray(data_batch)
  labels_batch = np.asarray(labels_batch)

  return data_batch, labels_batch

"""## Create Dataset for Discriminator 2

For discriminator 2 that has to ensure that the QR Code is scannable, we have to create a dataset of fake samples and the qr code text embedded in those.
So we need the following dataset:

consider the data_size i.e., the number of data samples in a batch is n, then dataset should contain n fake images
"""

def create_dataset_d2(fake_samples, qr_code_labels, data_size):
  fake_samples_trimmed = []
  qr_code_labels_trimmed = []
  for i in range (int(data_size)):
    
    fake_samples_trimmed.append(fake_samples[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])

  fake_samples_trimmed = np.asarray(fake_samples_trimmed)
  qr_code_labels_trimmed = np.asarray(qr_code_labels_trimmed)
  return fake_samples_trimmed, qr_code_labels_trimmed

"""## Create Dataset of Generator"""

def create_dataset_g(real_samples, qr_codes, qr_code_labels, data_size):
  real_samples_trimmed = []
  qr_codes_trimmed = []
  qr_code_labels_trimmed = []
  for i in range(int(data_size)):
    
    real_samples_trimmed.append(real_samples[i])
    qr_codes_trimmed.append(qr_codes[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])

  real_samples_trimmed = np.asarray(real_samples_trimmed)
  qr_codes_trimmed = np.asarray(qr_codes_trimmed)

  return qr_codes_trimmed, real_samples_trimmed, qr_code_labels_trimmed

"""## Generate Fake Samples Using Generator"""

def blend_data(qr_codes, host_images, num_samples):
  
  qr_codes = np.repeat(np.expand_dims(qr_codes, axis=-1), 1, axis=-1)
  
  host_images = host_images / 255.0
  average_blending_weights = []
  for i in range (qr_codes.shape[0]):
    
    image_1 = qr_codes[i]
    image_1 = np.resize(image_1, (256, 256, 3))
    image_2 = host_images[i]
    blending_weight = (image_1 + image_2) / 2.0
    average_blending_weights.append(blending_weight)
  average_blending_weights = np.array(average_blending_weights)
  return [qr_codes, host_images], average_blending_weights

#create only batch/2 samples
def generate_fake_samples (g_model, qr_codes, qr_code_labels, host_images, data_size):

  qr_codes_trimmed = []
  qr_code_labels_trimmed = []

  host_images_trimmed = []

  for i in range(int(data_size)):
    
    qr_codes_trimmed.append(qr_codes[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])
    host_images_trimmed.append(host_images[i])

  qr_codes_trimmed = np.asarray(qr_codes_trimmed)
  qr_code_labels_trimmed = np.asarray(qr_code_labels_trimmed)
  host_images_trimmed = np.asarray(host_images_trimmed)

  test_inputs, average_blending_weights = blend_data(qr_codes=qr_codes_trimmed, host_images=host_images_trimmed, num_samples = data_size) # For testing, we don't need targets
  fake_samples = g_model.predict(test_inputs, data_size)
  fake_sample_labels = np.zeros(int(data_size))

  return fake_samples, fake_sample_labels, qr_code_labels_trimmed, average_blending_weights

"""## Create Generator Model"""

def generator_model(input_shape_qr = (256,256,1), input_shape_host = (256,256,1)):
    # Define the input layers for the two images
    input_image1 = Input(shape=input_shape_qr, name='input_image1')
    input_image2 = Input(shape=input_shape_host, name='input_image2')

    reshaped_image1 = Reshape((256, 256, 1))(input_image1)

    # Concatenate the input images along the channel axis
    concatenated_images = Concatenate(axis=-1)([input_image1, input_image2])

    # Convolutional layers for blending
    x = Conv2D(64, (3, 3), activation='relu', padding='same')(concatenated_images)
    x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)  # Output with 3 channels (RGB)

    # Create the model
    model = Model(inputs = [input_image1, input_image2], outputs = x, name = 'Generator')
    model.summary()
    #keras.utils.plot_model(model, 'generator.png', show_shapes = True)
    return model



"""## Create Discriminator 1 Model (Perceptual Similarity)"""

def create_discriminator_model_for_perceptual_similarity(learning_rate, beta, input_shape_generator_output = (256,256,1)):

  input = keras.Input(shape = input_shape_generator_output)
  x = layers.Conv2D(64, (3,3), activation='relu', padding = 'same')(input)
  x = layers.Conv2D(128, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Conv2D(128, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Conv2D(256, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Flatten()(x)
  x = layers.Dropout(0.4)(x)
  output = layers.Dense(1, activation='sigmoid')(x)

  model = keras.Model(inputs = input, outputs = output, name = 'discriminator1')
  binary_crossentropy_loss = tf.keras.losses.BinaryCrossentropy()
  opt = Adam(lr=learning_rate, beta_1=beta)
  model.compile(optimizer=opt, loss=binary_crossentropy_loss, metrics=['accuracy'])
  model.summary()
  #keras.utils.plot_model(model, 'discriminator1.png', show_shapes = True)
  return model



"""## Create Discriminator 2 Model (QR Code Scanner)"""

def get_training_label_sizes(training_labels):
  training_label_sizes = list(map(lambda x: [len(x) - 1], training_labels))
  return training_label_sizes

def make_labels_for_position(labels, pos):
    chars = list(map(lambda x: x[pos] if pos < len(x) else EOI, labels)) # either a letter or EOI
    return list(map(lambda x: [ALL_CHAR_CLASSES.index(x)], chars)) # all classes are indexed [0..len(ALL_CHAR_CLASSES))

def define_split_with_size_multi_output_model(learning_rate, beta, input_shape_host = (256,256,1)):
    input_layer = keras.layers.Input(shape = input_shape_host, dtype='float', name='input_qr')
    flatten = keras.layers.Flatten(input_shape = input_shape_host, name='flatten')(input_layer)
    hidden_chars1 = keras.layers.Dense(441, activation='relu', name='hidden_chars1')(flatten)
    hidden_size = keras.layers.Dense(441, activation='relu', name='hidden_size')(flatten)
    size_output = keras.layers.Dense(MAX_SIZE, name='size_output')(hidden_size)

    # stop back propagation since size is independent from actual characters
    size_without_more_optimizations = tf.stop_gradient(size_output, name='size_wo_gradient')

    outputs = [size_output]
    for i in range(11):
        hidden_chars2 = keras.layers.Dense(21*21, activation='relu')(hidden_chars1)
        combined_char_inputs = keras.layers.concatenate([hidden_chars2, size_without_more_optimizations])
        char_output = keras.layers.Dense(len(ALL_CHAR_CLASSES), name='char' + str(i))(combined_char_inputs)
        outputs.append(char_output)

    multi_output_model = keras.Model(inputs=[input_layer], outputs=outputs)
    opt = Adam(lr=learning_rate, beta_1=beta)
    multi_output_model.compile(optimizer=opt,
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])

    multi_output_model.summary()
    #keras.utils.plot_model(multi_output_model, 'discriminator2.png', show_shapes = True)
    #print('type(multi_output_model): ', type(multi_output_model))
    return multi_output_model



"""## Create GAN Model"""

def create_gan_model(learning_rate_gan, beta_gan, learning_rate_discriminator1, beta_discriminator1, learning_rate_discriminator2, beta_discriminator2, loss_weights, input_shape_qr = (256, 256, 1), input_shape_host = (256,256,1), input_shape_generator_output = (256,256,1)):
  
  g_model = generator_model(input_shape_qr = (256, 256, 1), input_shape_host = (256,256,1))
  d1_model = create_discriminator_model_for_perceptual_similarity(learning_rate_discriminator1, beta_discriminator1, input_shape_generator_output = (256,256,1))
  #print('type(d1_model): ', type(d1_model))
  d2_model = define_split_with_size_multi_output_model(learning_rate_discriminator2, beta_discriminator2, input_shape_host = (256,256,1))
  #print('type(d2_model): ', type(d2_model))

  input_image1 = Input(shape=input_shape_qr, name='input_image1')
  input_image2 = Input(shape=input_shape_host, name='input_image2')

  generator = g_model([input_image1,input_image2])

  discriminator1 = d1_model(generator)
  discriminator2 = d2_model(generator)


  discriminator1.trainable = False
  for model_number in range (len(discriminator2)):
    model = discriminator2[model_number]
    model.trainable = False

  gan_model = keras.Model(inputs = [input_image1, input_image2], outputs = [discriminator1, discriminator2], name = 'gan_model')

  #keras.utils.plot_model(gan_model, 'gan_model.png', show_shapes=True)
  binary_crossentropy_loss = tf.keras.losses.BinaryCrossentropy()
  opt = Adam(lr = learning_rate_gan, beta_1 = beta_gan)
  gan_model.compile(optimizer = opt, loss=[binary_crossentropy_loss,tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)],metrics=['accuracy'])
  gan_model.summary()

  return g_model, d1_model, d2_model, gan_model


 
def save_plot(x_fake, X_real, qr_codes, epoch, n):
    
    fig, axs = plt.subplots(n, 3, figsize=(10, 10))
    for i in range(n):  # Loop through rows
        axs[i, 0].imshow(x_fake[i])  # Plot image from the first list
        axs[i, 0].axis('off')  # Turn off axis labels
        axs[i, 1].imshow(X_real[i].astype('uint8'))  # Plot image from the second list
        axs[i, 1].axis('off')  # Turn off axis labels
        axs[i, 2].imshow(qr_codes[i])  # Plot image from the third list
        axs[i, 2].axis('off')  # Turn off axis labels
        x_fake_rgb = np.stack([x_fake[i]] * 3, axis=-1)
        img_file = 'MNIST_blended/'+str(epoch)+'_'+str(i)+'.png'
        plt.imsave(img_file, x_fake_rgb.astype('float32'))

    # Add titles to subplots (optional)
    axs[0, 0].set_title('GAN Images')
    axs[0, 1].set_title('Real Images')
    axs[0, 2].set_title('QR Codes')

    # Adjust layout and display the plot
    #pyplot.tight_layout()
    filename = 'MNIST_blended_combined_output/mnist_e%03d.png' % (epoch+1)
    pyplot.savefig(filename)
    pyplot.close()

    

# evaluate the discriminator, plot generated images, save generator model
def summarize_performance(epoch, g_model, d1_model, d2_model, data_size):
  qr_code_images_expanded_dims_list = []
  # load real samples for Discriminator 1
  X_real, y_real = load_real_samples(target_shape = (256, 256), num_samples_to_take = data_size)
  #load QR Codes for Discriminator 2
  qr_codes, qr_code_labels = generate_dataset(data_size)
  qr_code_labels = [list(string) for string in qr_code_labels]
  evaluation_label_sizes = get_training_label_sizes(qr_code_labels)
  evaluation_labels_char0 = make_labels_for_position(qr_code_labels, 0)
  evaluation_labels_char1 = make_labels_for_position(qr_code_labels, 1)
  evaluation_labels_char2 = make_labels_for_position(qr_code_labels, 2)
  evaluation_labels_char3 = make_labels_for_position(qr_code_labels, 3)
  evaluation_labels_char4 = make_labels_for_position(qr_code_labels, 4)
  evaluation_labels_char5 = make_labels_for_position(qr_code_labels, 5)
  evaluation_labels_char6 = make_labels_for_position(qr_code_labels, 6)
  evaluation_labels_char7 = make_labels_for_position(qr_code_labels, 7)
  evaluation_labels_char8 = make_labels_for_position(qr_code_labels, 8)
  evaluation_labels_char9 = make_labels_for_position(qr_code_labels, 9)
  evaluation_labels_char10 = make_labels_for_position(qr_code_labels, 10)

  evaluation_labels = [
    np.asarray(evaluation_label_sizes),        # Size labels
    np.asarray(evaluation_labels_char0),       # Character 0 labels
    np.asarray(evaluation_labels_char1),       # Character 1 labels
    np.asarray(evaluation_labels_char2),       # Character 2 labels
    np.asarray(evaluation_labels_char3),       # and so on...
    np.asarray(evaluation_labels_char4),
    np.asarray(evaluation_labels_char5),
    np.asarray(evaluation_labels_char6),
    np.asarray(evaluation_labels_char7),
    np.asarray(evaluation_labels_char8),
    np.asarray(evaluation_labels_char9),
    np.asarray(evaluation_labels_char10)]
  # prepare fake examples
  x_fake, y_fake, _, _ = generate_fake_samples (g_model, qr_codes, evaluation_labels, host_images = X_real, data_size = global_batch_size)
  #### EVALUATE DISCRIMINATOR 1
  # evaluate discriminator 1 on real examples
  _, acc_real_d1 = d1_model.evaluate(X_real, y_real, verbose=0)
  # evaluate discriminator 1 on fake examples
  _, acc_fake_d1 = d1_model.evaluate(x_fake, y_fake, verbose=0)
  # summarize discriminator 1 performance
  print('>>>>>Accuracy discriminator 1 real: %.0f%%, fake: %.0f%%' % (acc_real_d1*100, acc_fake_d1*100))
  #### EVALUATE DISCRIMINATOR 2
  # evaluate discriminator 2 on real examples
  acc_fake_d2 = d2_model.evaluate(x_fake, y_fake, verbose=0)
  
  acc_real_d2 = d2_model.evaluate(qr_codes, evaluation_labels, verbose=0)#there is an error here because qr codes have dimensions 256 x 256, but the network expects an image of 256 x 256 x 3
  # evaluate discriminator 2 on fake examples
  
  # summarize discriminator 2 performance
  
  print('>>>>>Accuracy discriminator 2 real:', (acc_real_d2, acc_fake_d2))
  # save plot
  #print("x_fake.shape: ", x_fake.shape)
  save_plot(x_fake, X_real, qr_codes, epoch, n = x_fake.shape[0])
  
  
def data_size_batch_size_sample(config):
    batch_size = config["batch_size"]
    data_size = tune.sample_from(lambda _: max(batch_size, tune.randint(1, 512).sample()))
    return {"batch_size": batch_size, "data_size": data_size}

"""## Train GAN"""

# Fake Sample Label = 1
def train_gan(config, checkpoint_dir='MNIST_checkpoints'):
  d1_loss_list = []
  d2_loss_list = []
  g_loss_list = []
  image_width = 256
  image_height = 256
  #Get configuration parameters
  batch_size = config["batch_size"]
  epochs = config["epochs"]
  data_size = config["data_size"]
  gan_lr = config["gan_lr"]
  d1_lr = config["d1_lr"]
  gan_loss_weights = config["gan_loss_weights"]
  gan_beta = config["gan_beta"]
  d1_beta = config["d1_beta"]
  d2_lr = config["d2_lr"]
  d2_beta = config["d2_beta"]
  #create all the models
  g_model, d1_model, d2_model, gan_model = create_gan_model(gan_lr, gan_beta, d1_lr, d1_beta, d2_lr, d2_beta, gan_loss_weights)
  #load real samples
  images_real,labels_real = load_real_samples(target_shape = (image_width,image_height), num_samples_to_take = data_size)
  batch_per_epoch = int(data_size/batch_size)
  print(' batch_per_epoch', batch_per_epoch)
  (qr_codes, qr_code_labels) = generate_dataset(data_size)
  for i in range(epochs):
    print('Epoch = ', i)
    for j in range (batch_per_epoch):
      
      fake_samples, fake_sample_labels, qr_code_labels_trimmed, average_blending_weights = generate_fake_samples(g_model, qr_codes, qr_code_labels, host_images = images_real, data_size = data_size)
      #create dataset for discriminator 1
      discriminator_1_data_batch, discriminator_1_labels_batch = create_dataset_d1(real_samples = images_real, real_labels = labels_real, fake_samples = fake_samples, fake_labels = fake_sample_labels, data_size = data_size)
      #Create Dataset for discriminator 2
      discriminator_2_data_batch, discriminator_2_labels_batch = create_dataset_d2(fake_samples = fake_samples, qr_code_labels = qr_code_labels, data_size = data_size)
      #Update weights of discriminator 1
      d1_loss, _ = d1_model.train_on_batch(discriminator_1_data_batch, discriminator_1_labels_batch)
      print('d1_loss = ', d1_loss)
      d1_loss_list.append(d1_loss)
      #Preprocessing for Discriminator 2
      training_label_sizes = get_training_label_sizes(discriminator_2_labels_batch)
      training_labels_char0 = make_labels_for_position(discriminator_2_labels_batch, 0)
      training_labels_char1 = make_labels_for_position(discriminator_2_labels_batch, 1)
      training_labels_char2 = make_labels_for_position(discriminator_2_labels_batch, 2)
      training_labels_char3 = make_labels_for_position(discriminator_2_labels_batch, 3)
      training_labels_char4 = make_labels_for_position(discriminator_2_labels_batch, 4)
      training_labels_char5 = make_labels_for_position(discriminator_2_labels_batch, 5)
      training_labels_char6 = make_labels_for_position(discriminator_2_labels_batch, 6)
      training_labels_char7 = make_labels_for_position(discriminator_2_labels_batch, 7)
      training_labels_char8 = make_labels_for_position(discriminator_2_labels_batch, 8)
      training_labels_char9 = make_labels_for_position(discriminator_2_labels_batch, 9)
      training_labels_char10 = make_labels_for_position(discriminator_2_labels_batch, 10)
      #Update weights of Discriminator 2
      d2_loss, *x = d2_model.train_on_batch(discriminator_2_data_batch, [
            np.asarray(training_label_sizes),
            np.asarray(training_labels_char0),
            np.asarray(training_labels_char1),
            np.asarray(training_labels_char2),
            np.asarray(training_labels_char3),
            np.asarray(training_labels_char4),
            np.asarray(training_labels_char5),
            np.asarray(training_labels_char6),
            np.asarray(training_labels_char7),
            np.asarray(training_labels_char8),
            np.asarray(training_labels_char9),
            np.asarray(training_labels_char10)
        ])
      print('d2_loss = ', d2_loss)
      d2_loss_list.append(d2_loss)
      #Create Dataset for Generator
      generator_input1_batch, generator_input2_batch, qr_code_labels_trimmed = create_dataset_g(real_samples = images_real, qr_codes = qr_codes, qr_code_labels = qr_code_labels, data_size = data_size)
      training_label_sizes = get_training_label_sizes(qr_code_labels_trimmed)
      training_labels_char0 = make_labels_for_position(qr_code_labels_trimmed, 0)
      training_labels_char1 = make_labels_for_position(qr_code_labels_trimmed, 1)
      training_labels_char2 = make_labels_for_position(qr_code_labels_trimmed, 2)
      training_labels_char3 = make_labels_for_position(qr_code_labels_trimmed, 3)
      training_labels_char4 = make_labels_for_position(qr_code_labels_trimmed, 4)
      training_labels_char5 = make_labels_for_position(qr_code_labels_trimmed, 5)
      training_labels_char6 = make_labels_for_position(qr_code_labels_trimmed, 6)
      training_labels_char7 = make_labels_for_position(qr_code_labels_trimmed, 7)
      training_labels_char8 = make_labels_for_position(qr_code_labels_trimmed, 8)
      training_labels_char9 = make_labels_for_position(qr_code_labels_trimmed, 9)
      training_labels_char10 = make_labels_for_position(qr_code_labels_trimmed, 10)
      #Update Weights of Generator through GAN
      #print('generator_input1_batch.shape: ',generator_input1_batch.shape)
      #print('average_blending_weights', (average_blending_weights[0].shape))
      fake_sample_labels_inverted = np.ones(int(generator_input1_batch.shape[0]))
      g_loss, *x = gan_model.train_on_batch(x = [generator_input1_batch, generator_input2_batch],  y = [fake_sample_labels_inverted,[
            np.asarray(training_label_sizes),
            np.asarray(training_labels_char0),
            np.asarray(training_labels_char1),
            np.asarray(training_labels_char2),
            np.asarray(training_labels_char3),
            np.asarray(training_labels_char4),
            np.asarray(training_labels_char5),
            np.asarray(training_labels_char6),
            np.asarray(training_labels_char7),
            np.asarray(training_labels_char8),
            np.asarray(training_labels_char9),
            np.asarray(training_labels_char10)]])
    
      print('g_loss = ', g_loss)
      g_loss_list.append(g_loss)
      #Print Training Progress
      print('>%d, %d/%d, d1=%.3f,d2=%.3f, g=%.3f' % (i+1, j+1, batch_per_epoch, d1_loss, d2_loss, g_loss))
      #Summarize performance
    #if (i+1) % 10 == 0:
    #summarize_performance(i, g_model, d1_model, d2_model, data_size=data_size)
    
    session.report({"g_loss": np.mean(g_loss_list), "d1_loss": np.mean(d1_loss_list), "d2_loss": np.mean(d2_loss_list)})

#train_gan(g_model, d1_model, d2_model, gan_model, batch_size = global_batch_size, epochs = global_epochs, data_size = data_size)


# Define the scheduler
scheduler = ASHAScheduler(
    metric="g_loss",  # The metric to track
    mode="min",       # We want to minimize the generator loss
    max_t=10000,      # Maximum epochs
    grace_period=900, # Minimum epochs before stopping trials
    reduction_factor=2
)

# Define the search space
search_space = {
    "epochs": tune.choice([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]),  # Number of epochs
    "gan_lr": tune.loguniform(1e-5, 1e-1),  # Learning rate for GAN
    "d1_lr": tune.loguniform(1e-5, 1e-1),  # Learning rate for Discriminator 1
    "d1_beta": tune.loguniform(0.5, 0.9),  # decay rate for Discriminator 1
    "d2_lr": tune.loguniform(1e-5, 1e-1),  # Learning rate for Discriminator 1
    "d2_beta": tune.loguniform(0.5, 0.9),  # decay rate for Discriminator 1
    "gan_beta": tune.loguniform(0.5, 0.9),  # decay rate for generator
    "batch_size": tune.choice([32, 64, 128]),  # Batch size
    "data_size": tune.sample_from(lambda spec: max(spec.config["batch_size"], 1)),  # Data size: OLD VALUES :::: [10, 50, 100, 200]
    "gan_loss_weights": tune.grid_search([[0.99, 0.01], [0.95, 0.05], [0.75, 0.25], [0.60, 0.40], [0.5, 0.5]])  # Weights for generator and discriminator losses
}


tuner = tune.Tuner(
    tune.with_resources(train_gan, resources={"cpu": 5, "gpu": 0}),  # Define CPU and GPU resources for each trial
    param_space=search_space,  # Search space defined above
    tune_config=tune.TuneConfig(
        num_samples=2,                # Number of different configurations to sample
        scheduler=scheduler,           # Use the ASHAScheduler
        max_concurrent_trials=1        # Limit the number of concurrent trials
    ),
    run_config=RunConfig(
        stop={"training_iteration": 100},  # Maximum training iterations per trial
        local_dir="./ray_results_mnist",   # Specify where to save results
    )
)

# Run the tuner
results = tuner.fit()

# Get the best configuration
best_config = results.get_best_result(metric="g_loss", mode="min").config
print("Best hyperparameters: ", best_config)

# Save the best configuration
import json
with open("best_gan_config_mnist.json", "w") as f:
    json.dump(best_config, f)

