import qrcode
import random
import string

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Concatenate, Conv2D, UpSampling2D, Reshape, Dense, LeakyReLU, ZeroPadding2D
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError, SparseCategoricalCrossentropy
from tensorflow.keras.applications import VGG16

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

import cv2
import os
from PIL import Image

# Fix a runtime bug on macOS
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

import tensorflow_datasets as tfds
from matplotlib import pyplot

"""# Global Speicfications"""
data_size = 10 #no of samples in a batch
global_batch_size = 10 #no of batches
global_epochs = 6500
image_width = 256
image_height = 256
channels = 3
test_data_size = 5

"""# Create Directories For Storing Training Progress"""
os.makedirs("dl_gan_static_train_inputs_outputs", exist_ok=True)
os.makedirs("dl_gan_static_train_outputs", exist_ok=True)

os.makedirs("dl_gan_static_train_inputs_outputs_e1", exist_ok=True)
os.makedirs("dl_gan_static_train_outputs_e1", exist_ok=True)

"""# Functions

## Load Real Samples
"""

def load_real_samples(target_shape, num_samples_to_take = 500, name = 'tf_flowers'):
    constant_label = 1
    caltech_builder = tfds.builder(name)
    caltech_builder.download_and_prepare()
    dataset = caltech_builder.as_dataset(split='train')

    shuffled_dataset = dataset.shuffle(buffer_size=num_samples_to_take)
    subset_dataset = shuffled_dataset.take(num_samples_to_take)

    num_images_in_subset = tf.data.experimental.cardinality(subset_dataset).numpy()
    images, labels = [], []
    for example in subset_dataset:
        example['image'] = tf.image.resize(example['image'], target_shape)
        images.append(example['image'].numpy())
        labels.append(constant_label)

    images_array = np.array(images)
    labels_array = np.array(labels, dtype=np.int64)

    num_images_in_subset = len(images_array)
    print(f"Number of images in subset_dataset_with_labels: {num_images_in_subset}")

    return images_array, labels_array

"""## Generate QR Codes"""

LETTERS = string.ascii_lowercase + ' ' # letters and space
EOI = '#' # end of input
MAX_SIZE = 11 # max input/output size
ALL_CHAR_CLASSES = LETTERS + EOI # all available classes

# define a function for a QR code generation
# box_size is an option to manage size of an output image
def make_qr(text, box_size=12, target_size=(128, 128)):
    qr = qrcode.QRCode(
        version=1,
        box_size=box_size,
        border=0
    )
    qr.add_data(text)
    qr.make(fit=True)
    qr_image = qr.make_image(fill_color="black", back_color="white").convert('RGB')

    # Resize the QR code image to the target size
    resized_image = qr_image.resize(target_size)
    
    # Convert RGBA to RGB
    #rgb_image = resized_image.convert('RGB')

    return np.asarray(resized_image, dtype='uint8')

# a function to generate a train data set
# output: (numpy array of images, list of corresponding texts)
def generate_dataset(n_of_samples, min_size = 1, max_size = 11):
    data = []
    labels = []
    report_step = int(n_of_samples * .1)
    report = report_step
    print("Generating")
    for i in range(n_of_samples):
        if i == report:
            report = report + report_step
        #select size of the string to be embedded in a QR Code randonly between 1 and 11
        size = random.randint(min_size, max_size)
        #generate the string using random letters and space
        s = ''.join(random.choice(LETTERS) for i in range(size))
        #make the QR Code
        img = make_qr(s)
        #ensure the size is 256 x 256 pixels
        #assert img.size == (256,256)
        qr = np.asarray(img, dtype='float')
        #Append the QR code to the data list
        data.append(qr)
        #Append the String of random size generated using random letters to the label list
        labels.append(s)
    print("Done:", "100", "%")
    return (np.asarray(data), labels)

"""## Create Dataset for Discriminator 1

For Discriminator 1, that is supposed to ensure that the image generated by the generator is similar to the host image, we need the following dataset:

consider the data_size i.e., the number of data samples in a batch is n, then dataset should contain n/2 real images and n/2 fake images.
"""

def create_dataset_d1(real_samples, real_labels, fake_samples, fake_labels, data_size = data_size):
  data_batch = []
  labels_batch = []
  for i in range (int(data_size/2)):
    random_number = random.randint(0, int(data_size/2))
    data_batch.append(real_samples[random_number])
    labels_batch.append(real_labels[random_number])

  for i in range (int(data_size/2)):
    random_number = random.randint(0, int(data_size/2))
    data_batch.append(fake_samples[random_number])
    labels_batch.append(fake_labels[random_number])

  data_batch = np.asarray(data_batch)
  labels_batch = np.asarray(labels_batch)

  return data_batch, labels_batch

"""## Create Dataset for Discriminator 2

For discriminator 2 that has to ensure that the QR Code is scannable, we have to create a dataset of fake samples and the qr code text embedded in those.
So we need the following dataset:

consider the data_size i.e., the number of data samples in a batch is n, then dataset should contain n fake images
"""

def create_dataset_d2(fake_samples, qr_code_labels, data_size = data_size):
  fake_samples_trimmed = []
  qr_code_labels_trimmed = []
  for i in range (int(data_size)):
    fake_samples_trimmed.append(fake_samples[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])

  fake_samples_trimmed = np.asarray(fake_samples_trimmed)
  qr_code_labels_trimmed = np.asarray(qr_code_labels_trimmed)
  return fake_samples_trimmed, qr_code_labels_trimmed

"""## Create Dataset of Generator"""

def create_dataset_g(real_samples, qr_codes, qr_code_labels, data_size = data_size):
  real_samples_trimmed = []
  qr_codes_trimmed = []
  qr_code_labels_trimmed = []
  for i in range(int(data_size)):
    real_samples_trimmed.append(real_samples[i])
    qr_codes_trimmed.append(qr_codes[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])

  real_samples_trimmed = np.asarray(real_samples_trimmed)
  qr_codes_trimmed = np.asarray(qr_codes_trimmed)

  return qr_codes_trimmed, real_samples_trimmed, qr_code_labels_trimmed

"""## Generate Fake Samples Using Generator"""

def blend_data(qr_codes, host_images, num_samples):
  host_images = host_images / 255.0
  average_blending_weights = []
  for i in range (qr_codes.shape[0]):
    image_1 = qr_codes[i]
    image_1 = np.resize(image_1, (256, 256, 3))
    image_2 = host_images[i]
    blending_weight = (image_1 + image_2) / 2.0
    average_blending_weights.append(blending_weight)
  average_blending_weights = np.array(average_blending_weights)
  return [qr_codes, host_images], average_blending_weights

#create only batch/2 samples
def generate_fake_samples (g_model, qr_codes, qr_code_labels, host_images, data_size = data_size):

  qr_codes_trimmed = []
  qr_code_labels_trimmed = []

  host_images_trimmed = []

  for i in range(int(data_size)):
    qr_codes_trimmed.append(qr_codes[i])
    qr_code_labels_trimmed.append(qr_code_labels[i])
    host_images_trimmed.append(host_images[i])

  qr_codes_trimmed = np.asarray(qr_codes_trimmed)
  qr_code_labels_trimmed = np.asarray(qr_code_labels_trimmed)
  host_images_trimmed = np.asarray(host_images_trimmed)

  test_inputs, average_blending_weights = blend_data(qr_codes=qr_codes_trimmed, host_images=host_images_trimmed, num_samples = data_size) # For testing, we don't need targets
  fake_samples = g_model.predict(test_inputs, data_size)
  fake_sample_labels = np.ones(int(data_size))

  return fake_samples, fake_sample_labels, qr_code_labels_trimmed, average_blending_weights, host_images_trimmed

"""## Create Generator Model"""

def generator_model(input_shape_qr=(128, 128, 3), input_shape_host=(256, 256, 3)):
    # Define the input layers for the two images
    input_image1 = Input(shape=input_shape_qr, name='input_image1')
    input_image2 = Input(shape=input_shape_host, name='input_image2')

    # Calculate padding needed to center the QR code on the host image
    pad_height = (input_shape_host[0] - input_shape_qr[0]) // 2
    pad_width = (input_shape_host[1] - input_shape_qr[1]) // 2

    # Pad the QR code to match the host image size
    padded_qr = ZeroPadding2D(padding=((pad_height, pad_height), (pad_width, pad_width)))(input_image1)

    # Ensure padded QR code is of correct size in case of odd dimensions
    if padded_qr.shape[1] != input_shape_host[0] or padded_qr.shape[2] != input_shape_host[1]:
        padded_qr = ZeroPadding2D(padding=((0, input_shape_host[0] - padded_qr.shape[1]),
                                           (0, input_shape_host[1] - padded_qr.shape[2])))(padded_qr)

    # Concatenate the input images along the channel axis
    concatenated_images = Concatenate(axis=-1)([padded_qr, input_image2])

    # Convolutional layers for blending
    x = Conv2D(64, (3, 3), activation='relu', padding='same')(concatenated_images)
    x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = Conv2D(3, (3, 3), activation='sigmoid', padding='same')(x)  # Output with 3 channels (RGB)

    # Create the model
    model = Model(inputs=[input_image1, input_image2], outputs=x, name='Generator')
    model.summary()
    # keras.utils.plot_model(model, 'generator.png', show_shapes=True)
    return model

generator_model()

"""## Create Discriminator 1 Model (Perceptual Similarity)"""

def create_discriminator_model_for_perceptual_similarity(input_shape_generator_output = (256,256,3)):

  base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape_generator_output)

    # Freeze the layers in the pre-trained model
  for layer in base_model.layers:
        layer.trainable = False
  input = keras.Input(shape = input_shape_generator_output)
  x = base_model(input)
  x = layers.Conv2D(64, (3,3), activation='relu', padding = 'same', strides = 2)(x)
  #x = layers.Conv2D(64, (3,3), activation='relu', padding = 'same', strides = 2)(x)
  x = layers.Conv2D(128, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Conv2D(256, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Conv2D(128, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Conv2D(64, (3,3), activation='relu', padding = 'same')(x)
  x = layers.Flatten()(x)
  x = layers.Dropout(0.4)(x)
  output = layers.Dense(1, activation='sigmoid')(x)

  model = keras.Model(inputs = input, outputs = output, name = 'discriminator1')
  binary_crossentropy_loss = tf.keras.losses.BinaryCrossentropy()

  model.compile(optimizer='adam', loss=binary_crossentropy_loss, metrics=['accuracy'])
  model.summary()
  #keras.utils.plot_model(model, 'discriminator1.png', show_shapes = True)
  return model

create_discriminator_model_for_perceptual_similarity()

"""## Create Discriminator 2 Model (QR Code Scanner)"""

def get_training_label_sizes(training_labels):
  training_label_sizes = list(map(lambda x: [len(x) - 1], training_labels))
  return training_label_sizes

def make_labels_for_position(labels, pos):
    chars = list(map(lambda x: x[pos] if pos < len(x) else EOI, labels)) # either a letter or EOI
    return list(map(lambda x: [ALL_CHAR_CLASSES.index(x)], chars)) # all classes are indexed [0..len(ALL_CHAR_CLASSES))

def define_split_with_size_multi_output_model(input_shape_host = (256,256,3)):
    input_layer = keras.layers.Input(shape = input_shape_host, dtype='float', name='input_qr')
    flatten = keras.layers.Flatten(input_shape = input_shape_host, name='flatten')(input_layer)
    hidden_chars1 = keras.layers.Dense(441, activation='relu', name='hidden_chars1')(flatten)
    hidden_size = keras.layers.Dense(441, activation='relu', name='hidden_size')(flatten)
    size_output = keras.layers.Dense(MAX_SIZE, name='size_output')(hidden_size)

    # stop back propagation since size is independent from actual characters
    size_without_more_optimizations = tf.stop_gradient(size_output, name='size_wo_gradient')

    outputs = [size_output]
    for i in range(11):
        hidden_chars2 = keras.layers.Dense(21*21, activation='relu')(hidden_chars1)
        combined_char_inputs = keras.layers.concatenate([hidden_chars2, size_without_more_optimizations])
        char_output = keras.layers.Dense(len(ALL_CHAR_CLASSES), name='char' + str(i))(combined_char_inputs)
        outputs.append(char_output)

    multi_output_model = keras.Model(inputs=[input_layer], outputs=outputs)

    multi_output_model.compile(optimizer='adam',
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])

    multi_output_model.summary()
    #keras.utils.plot_model(multi_output_model, 'discriminator2.png', show_shapes = True)
    return multi_output_model

define_split_with_size_multi_output_model()

"""## Create GAN Model"""

def create_gan_model(input_shape_qr=(128, 128, 3), input_shape_host=(256, 256, 3), input_shape_generator_output=(256, 256, 3)):
    g_model = generator_model(input_shape_qr=input_shape_qr, input_shape_host=input_shape_host)
    d2_model = define_split_with_size_multi_output_model(input_shape_host=input_shape_host)

    input_image1 = Input(shape=input_shape_qr, name='input_image1')
    input_image2 = Input(shape=input_shape_host, name='input_image2')

    generator_output = g_model([input_image1, input_image2])
    discriminator2_output = d2_model(generator_output)

    for model in discriminator2_output:
        model.trainable = False

    gan_model = keras.Model(inputs=[input_image1, input_image2], outputs=[generator_output, discriminator2_output], name='gan_model')

    mse_loss = MeanSquaredError()
    sparse_categorical_crossentropy_loss = SparseCategoricalCrossentropy(from_logits=True)
    opt = Adam(lr=0.0002, beta_1=0.5)
    losses = [mse_loss] + [sparse_categorical_crossentropy_loss] * len(discriminator2_output)
    gan_model.compile(optimizer=opt, loss=losses, metrics=['accuracy'],loss_weights=[0.95, 0.05])
    gan_model.summary()

    return g_model, d2_model, gan_model

g_model, d2_model, gan_model = create_gan_model()

 
 ### Start ADP Calculations
def reverse_labels_from_position(indices):
    # indices: A list of lists containing the indices of characters

    # Map the indices back to the characters using ALL_CHAR_CLASSES
    chars = list(map(lambda x: ALL_CHAR_CLASSES[x[0]], indices))
    
    # Combine the characters to form the labels
    return chars
def convert_labels_to_qr_code(evaluation_labels, max_length=MAX_SIZE):
    predicted_labels = []
    for i in range(len(evaluation_labels)):
      # Extract the label sizes (the first array in evaluation_labels)
      label_sizes = evaluation_labels[i].flatten()

      # Initialize list to store the decoded QR code strings
      qr_code_strings = []

      # Iterate over each label (indexed by i)
      for i in range(len(label_sizes)):
          qr_code = ""
          for pos in range(max_length):
              if pos >= label_sizes[i]:  # Stop if we have reached the label size
                  break
              # Find the character corresponding to the index in ALL_CHAR_CLASSES
              index = evaluation_labels[pos + 1][i][0]
              qr_code += ALL_CHAR_CLASSES[index]
          qr_code_strings.append(qr_code)
    predicted_labels.append(qr_code_strings)
    return predicted_labels


def adp(g_model, discriminator_model):
    adp_values_avg = 0
    for i in range(10):
        host_images_array, discriminator_1_labels_array = load_real_samples(target_shape = (256, 256), num_samples_to_take = 1)
        
        qr_codes, qr_code_labels = generate_dataset(n_of_samples = 1)
        print('qr_code_labels: ', qr_code_labels)
        qr_code_labels = [list(string) for string in qr_code_labels]
        print('qr_code_labels: ', qr_code_labels)
        evaluation_label_sizes = get_training_label_sizes(qr_code_labels)
        evaluation_labels_char0 = make_labels_for_position(qr_code_labels, 0)
        evaluation_labels_char1 = make_labels_for_position(qr_code_labels, 1)
        evaluation_labels_char2 = make_labels_for_position(qr_code_labels, 2)
        evaluation_labels_char3 = make_labels_for_position(qr_code_labels, 3)
        evaluation_labels_char4 = make_labels_for_position(qr_code_labels, 4)
        evaluation_labels_char5 = make_labels_for_position(qr_code_labels, 5)
        evaluation_labels_char6 = make_labels_for_position(qr_code_labels, 6)
        evaluation_labels_char7 = make_labels_for_position(qr_code_labels, 7)
        evaluation_labels_char8 = make_labels_for_position(qr_code_labels, 8)
        evaluation_labels_char9 = make_labels_for_position(qr_code_labels, 9)
        evaluation_labels_char10 = make_labels_for_position(qr_code_labels, 10)

        evaluation_labels = [
            np.asarray(evaluation_label_sizes),        # Size labels
            np.asarray(evaluation_labels_char0),       # Character 0 labels
            np.asarray(evaluation_labels_char1),       # Character 1 labels
            np.asarray(evaluation_labels_char2),       # Character 2 labels
            np.asarray(evaluation_labels_char3),       # and so on...
            np.asarray(evaluation_labels_char4),
            np.asarray(evaluation_labels_char5),
            np.asarray(evaluation_labels_char6),
            np.asarray(evaluation_labels_char7),
            np.asarray(evaluation_labels_char8),
            np.asarray(evaluation_labels_char9),
            np.asarray(evaluation_labels_char10)]
        print('qr_codes.shape: ',qr_codes.shape)
        print('host_images_array.shape: ', host_images_array.shape)
        #qr_codes = qr_codes.reshape(1, qr_codes.shape[0], qr_codes.shape[1], qr_codes.shape[2])
        #composite_images = g_model.predict([qr_codes, host_images_array])
        composite_images, y_fake, _, _, _ = generate_fake_samples (g_model, qr_codes, evaluation_labels, host_images = host_images_array, data_size = 1)
        ###save these composite images in a separate folder
        filename = f'generator_test_static/{i}.png'
        plt.imsave(filename, composite_images)
        predictions = discriminator_model.predict(composite_images)
        predicted_label_index_list = []
        for i in range(1, len(predictions)):# This is the output of the discrimiantor model  which is a list with 12 entries. First is for size pred and rest for character preds
            #print('i: ',i)
            labels_for_current_image = predictions[i] #this is  numpy array (1,28)
            for j in range (len(labels_for_current_image)):
                labels_for_current_char = labels_for_current_image[j]#This is the individual character
                print('labels_for_current_char', labels_for_current_char)
                predicted_label_index = np.argmax(labels_for_current_char)
                predicted_label_index_list.append([predicted_label_index])
        print('predicted_label_index_list: ', predicted_label_index_list)
        predicted_labels = reverse_labels_from_position(predicted_label_index_list)
        print('predicted_labels: ', predicted_labels)
        qr_code_labels = [item for sublist in qr_code_labels for item in sublist]
        correct_symbols = 0
        total_symbols = len(qr_code_labels)
        print('total_symbols: ', total_symbols)
        print('qr_code_labels: ', qr_code_labels)
        
        for i in range(len(qr_code_labels)):
          
          if(qr_code_labels[i] == predicted_labels[i]):
                correct_symbols = correct_symbols + 1
          # call the ADP function
          #actual_counts = qr_code_labels[0]
          #predicted_counts = predicted_labels[0]
          
          adp_values = (correct_symbols / total_symbols)
          print(f'ADP Value for image = {adp_values}')
          adp_values_avg = adp_values_avg + adp_values
          
    adp_values_avg = adp_values_avg/10
    print(f'Average ADP Values = {adp_values_avg}')
    #create generator_test images -------- flowers dataset
    X_real, discriminator_1_labels_array = load_real_samples(target_shape = (256, 256), num_samples_to_take = 5)
    qr_codes, qr_code_labels = generate_dataset(n_of_samples = 5)
    #x_fake = g_model.predict([qr_codes, X_real],5)
    x_fake, y_fake, _, _, _ = generate_fake_samples (g_model, qr_codes, qr_code_labels, host_images = X_real, data_size = 5)
    save_plot(x_fake, X_real, qr_codes, epoch = 1, n = 5)
        #create generator_test images -------- cats_vs_dogs dataset
    X_real, discriminator_1_labels_array = load_real_samples(target_shape = (256, 256), num_samples_to_take = 5, name = 'cats_vs_dogs')
    qr_codes, qr_code_labels = generate_dataset(n_of_samples = 5)
    x_fake, y_fake, _, _, _ = generate_fake_samples (g_model, qr_codes, qr_code_labels, host_images = X_real, data_size = 5)
    save_plot(x_fake, X_real, qr_codes, epoch = 1, n = 5)
    
        
#-x-x-x-x ADP Calculations -x-x-x-x
def prepare_qr_code_batch(qr_codes, target_shape=(256, 256, 3)):
    def pad_and_resize_single_qr_code(qr_code):
        qr_code = tf.image.resize_with_crop_or_pad(qr_code, target_shape[0], target_shape[1])
        return qr_code
    
    # Apply padding and resizing to each QR code in the batch
    padded_qr_codes = np.array([pad_and_resize_single_qr_code(qr_code).numpy() for qr_code in qr_codes])
    return padded_qr_codes
 
def save_plot(x_fake, X_real, qr_codes, epoch, n):
    if(epoch == 1):
        print('x_fake.shape: ', x_fake.shape)
        print('X_real.shape: ', X_real.shape)
        print('qr_codes.shape: ', qr_codes.shape)
        fig, axs = plt.subplots(3, n, figsize=(8, 5))
        for i in range(n):  # Loop through rows
            axs[0, i].imshow(X_real[i].astype('uint8'))  # Plot image from the second list
            axs[0, i].axis('off')  # Turn off axis labels
            axs[1, i].imshow(qr_codes[i])  # Plot image from the third list
            axs[1, i].axis('off')  # Turn off axis labels
            axs[2, i].imshow(x_fake[i])  # Plot image from the first list
            axs[2, i].axis('off')  # Turn off axis labels
            random_number_1 = random.randint(0, 100)
            img_file = 'dl_gan_static_train_inputs_outputs_e1/'+str(random_number_1)+'.png'
            plt.imsave(img_file, x_fake[i])


        # Add titles to subplots (optional)
        axs[0, 0].set_title('Real Images')
        axs[1, 0].set_title('QR Codes')
        axs[2, 0].set_title('GAN Images')
        # Adjust layout and display the plot
        #pyplot.tight_layout()
        plt.tight_layout(pad=0.5)  # pad=0 minimizes padding between subplots
        plt.subplots_adjust(wspace=0.5)
        random_number_2 = random.randint(0, 100)
        filename = f'dl_gan_static_train_outputs_e1/{random_number_2}.png'
        pyplot.savefig(filename)
        pyplot.close()
    else:
        print('x_fake.shape: ', x_fake.shape)
        print('X_real.shape: ', X_real.shape)
        print('qr_codes.shape: ', qr_codes.shape)
        fig, axs = plt.subplots(3, n, figsize=(8, 5))
        for i in range(n):  # Loop through rows
            axs[0, i].imshow(X_real[i].astype('uint8'))  # Plot image from the second list
            axs[0, i].axis('off')  # Turn off axis labels
            axs[1, i].imshow(qr_codes[i])  # Plot image from the third list
            axs[1, i].axis('off')  # Turn off axis labels
            axs[2, i].imshow(x_fake[i])  # Plot image from the first list
            axs[2, i].axis('off')  # Turn off axis labels
            img_file = 'dl_gan_static_train_inputs_outputs/'+str(epoch)+'_'+str(i)+'.png'
            plt.imsave(img_file, x_fake[i])


        # Add titles to subplots (optional)
        axs[0, 0].set_title('Real Images')
        axs[1, 0].set_title('QR Codes')
        axs[2, 0].set_title('GAN Images')
        # Adjust layout and display the plot
        #pyplot.tight_layout()
        plt.tight_layout(pad=0.5)  # pad=0 minimizes padding between subplots
        plt.subplots_adjust(wspace=0.5)
        filename = 'dl_gan_static_train_outputs/flowers_e%03d.png' % (epoch+1)
        pyplot.savefig(filename)
        pyplot.close()

# evaluate the discriminator, plot generated images, save generator model
def summarize_performance(epoch, g_model, d2_model, data_size=test_data_size):
  qr_code_images_expanded_dims_list = []
  # load real samples for Discriminator 1
  X_real, y_real = load_real_samples(target_shape = (256, 256), num_samples_to_take = data_size)
  #load QR Codes for Discriminator 2
  qr_codes, qr_code_labels = generate_dataset(data_size)
  qr_code_labels = [list(string) for string in qr_code_labels]
  evaluation_label_sizes = get_training_label_sizes(qr_code_labels)
  evaluation_labels_char0 = make_labels_for_position(qr_code_labels, 0)
  evaluation_labels_char1 = make_labels_for_position(qr_code_labels, 1)
  evaluation_labels_char2 = make_labels_for_position(qr_code_labels, 2)
  evaluation_labels_char3 = make_labels_for_position(qr_code_labels, 3)
  evaluation_labels_char4 = make_labels_for_position(qr_code_labels, 4)
  evaluation_labels_char5 = make_labels_for_position(qr_code_labels, 5)
  evaluation_labels_char6 = make_labels_for_position(qr_code_labels, 6)
  evaluation_labels_char7 = make_labels_for_position(qr_code_labels, 7)
  evaluation_labels_char8 = make_labels_for_position(qr_code_labels, 8)
  evaluation_labels_char9 = make_labels_for_position(qr_code_labels, 9)
  evaluation_labels_char10 = make_labels_for_position(qr_code_labels, 10)

  evaluation_labels = [
    np.asarray(evaluation_label_sizes),        # Size labels
    np.asarray(evaluation_labels_char0),       # Character 0 labels
    np.asarray(evaluation_labels_char1),       # Character 1 labels
    np.asarray(evaluation_labels_char2),       # Character 2 labels
    np.asarray(evaluation_labels_char3),       # and so on...
    np.asarray(evaluation_labels_char4),
    np.asarray(evaluation_labels_char5),
    np.asarray(evaluation_labels_char6),
    np.asarray(evaluation_labels_char7),
    np.asarray(evaluation_labels_char8),
    np.asarray(evaluation_labels_char9),
    np.asarray(evaluation_labels_char10)]
  # prepare fake examples
  x_fake, y_fake, _, _, _ = generate_fake_samples (g_model, qr_codes, evaluation_labels, host_images = X_real, data_size = test_data_size)
  
  qr_codes = prepare_qr_code_batch(qr_codes)
  acc_real_d2 = d2_model.evaluate(qr_codes, evaluation_labels, verbose=0)
  #print('>>>>>Accuracy discriminator 2 real:', (acc_real_d2, acc_fake_d2))
  # save plot
  print("x_fake.shape: ", x_fake.shape)
  save_plot(x_fake, X_real, qr_codes, epoch, n = x_fake.shape[0])
  # save the generator model tile file
  if (epoch == global_epochs - 1):
    filename = 'generator_flowers_static_e_%03d.h5' % (epoch + 1)
    g_model.save(filename)
    print("Generator Model Saved...")

  
def plot_losses(d2_loss_list, g_loss_list, mse_loss_list, global_epochs):
    epochs_list = list(range(global_epochs))
    
    # Plot the losses
    plt.figure(figsize=(10, 6))  # Set figure size
    plt.plot(epochs_list, d2_loss_list, color='green', label='D2 Loss')
    plt.plot(epochs_list, g_loss_list, color='blue', label='GAN Loss')
    plt.plot(epochs_list, mse_loss_list, color='red', label='MSE Loss')

    # Add title and labels
    plt.title('Loss over Epochs - Static Color and Position)', fontsize=16)
    plt.xlabel('Epochs', fontsize=14)
    plt.ylabel('Loss', fontsize=14)

    # Add grid lines
    plt.grid(True, linestyle='--', alpha=0.6)

    # Add a legend to differentiate the lines
    plt.legend(loc='upper right', fontsize=12)

    # Save the plot
    plt.savefig('loss_plot_flowers_static.png')
    plt.close()
  


"""## Train GAN"""

import pandas as pd

def train_gan(g_model, d2_model, gan_model, batch_size=64, epochs=100, data_size=1000, image_width=256, image_height=256):
    d2_loss_list = []
    g_loss_list = []
    mse_loss_list = []  # Track MSE loss separately

    images_real, labels_real = load_real_samples(target_shape=(image_width, image_height), num_samples_to_take=data_size)
    batch_per_epoch = int(data_size / batch_size)
    qr_codes, qr_code_labels = generate_dataset(data_size)

    for i in range(epochs):
        print('epoch = ', i)
        for j in range(batch_per_epoch):
            fake_samples, fake_sample_labels, qr_code_labels_trimmed, average_blending_weights, host_images_trimmed = generate_fake_samples(
                g_model, qr_codes, qr_code_labels, host_images=images_real, data_size=data_size)

            discriminator_2_data_batch, discriminator_2_labels_batch = create_dataset_d2(
                fake_samples=fake_samples, qr_code_labels=qr_code_labels, data_size=data_size)

            training_label_sizes = get_training_label_sizes(discriminator_2_labels_batch)
            training_labels_char = [make_labels_for_position(discriminator_2_labels_batch, k) for k in range(11)]

            d2_loss, *x = d2_model.train_on_batch(discriminator_2_data_batch, [
                np.asarray(training_label_sizes)] + [np.asarray(label) for label in training_labels_char])
            d2_loss_list.append(d2_loss)

            generator_input1_batch, generator_input2_batch, qr_code_labels_trimmed = create_dataset_g(
                real_samples=images_real, qr_codes=qr_codes, qr_code_labels=qr_code_labels, data_size=data_size)

            training_label_sizes = get_training_label_sizes(qr_code_labels_trimmed)
            training_labels_char = [make_labels_for_position(qr_code_labels_trimmed, k) for k in range(11)]

            # Ensure only two inputs are provided
            g_loss, mse_loss, *x = gan_model.train_on_batch(
                x=[generator_input1_batch, generator_input2_batch],
                y=[generator_input2_batch, [np.asarray(training_label_sizes)] + [np.asarray(label) for label in training_labels_char]])
            
            g_loss_list.append(g_loss)
            mse_loss_list.append(mse_loss)  # Save the MSE loss component

            print('>%d, %d/%d, d2=%.3f, g=%.3f, mse=%.3f' % (i + 1, j + 1, batch_per_epoch, d2_loss, g_loss, mse_loss))

        if (i + 1) % 10 == 0:
            summarize_performance(i, g_model, d2_model, data_size=data_size)
    adp(g_model, d2_model)
    plot_losses(d2_loss_list, g_loss_list, mse_loss_list, epochs)
    
    # Save losses to CSV
    losses_df = pd.DataFrame({
        'd2_loss': d2_loss_list,
        'g_loss': g_loss_list,
        'mse_loss': mse_loss_list
    })
    losses_df.to_csv('losses.csv', index=False)
    print("losses_dual_loss_gan_static.csv")

train_gan(g_model, d2_model, gan_model, batch_size = global_batch_size, epochs = global_epochs, data_size = data_size)
